# Generated by Django 5.1.5 on 2025-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
